Rust 2018!
andrewjj20/pubsub pull request #5
Opened 2018-07-19 04:01 UTC by andrewjj20

2018-07-19 18:18 UTC, yaahc requested changes
can you split this back into two PRs?

2018-07-21 01:23 UTC, andrewjj20 commented
It was just waiting on the one in front of it to go in. They are both in now.

2018-07-21 01:49 UTC, yaahc approved these changes

2018-07-21 01:49 UTC, yaahallo commented on src/find_service.rs
> +        use crate::find_service::ServerError::*;
Might make sense to have a use for this

2018-07-21 19:24 UTC, merged